import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

export interface PerformanceReportData {
    employeeName: string;
    department: string;
    weekStart: string;
    weekEnd: string;
    score: number;
    tasksTotal: number;
    tasksCompleted: number;
    tasksOverdue: number;
    level: string;
}

export function generatePerformancePDF(data: PerformanceReportData) {
    const doc = new jsPDF();
    const timestamp = format(new Date(), 'yyyy-MM-dd HH:mm');

    // Branding & Header
    doc.setFillColor(31, 41, 55); // Slate 900
    doc.rect(0, 0, 210, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('JEWELMATRIX OPERATIONAL REPORT', 15, 25);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated on: ${timestamp}`, 150, 25);

    // Employee Info Section
    doc.setTextColor(31, 41, 55);
    doc.setFontSize(16);
    doc.text('Performance Summary', 15, 55);

    doc.setDrawColor(229, 231, 235);
    doc.line(15, 60, 195, 60);

    const infoRows = [
        ['Employee Name:', data.employeeName],
        ['Department:', data.department],
        ['Reporting Period:', `${data.weekStart} to ${data.weekEnd}`],
        ['Overall Efficiency:', `${data.score}%`],
        ['Assigned Level:', data.level]
    ];

    autoTable(doc, {
        body: infoRows,
        startY: 65,
        theme: 'plain',
        styles: { fontSize: 11, cellPadding: 3 },
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50 } }
    });

    // Metrics Grid
    doc.setFontSize(14);
    doc.text('Activity Metrics', 15, (doc as any).lastAutoTable.finalY + 15);

    const metricData = [
        ['Total Units Assigned', data.tasksTotal.toString()],
        ['Units Successfully Completed', data.tasksCompleted.toString()],
        ['Units Overdue', data.tasksOverdue.toString()],
        ['Completion Rate', `${Math.round((data.tasksCompleted / (data.tasksTotal || 1)) * 100)}%`]
    ];

    autoTable(doc, {
        head: [['Metric', 'Value']],
        body: metricData,
        startY: (doc as any).lastAutoTable.finalY + 20,
        theme: 'grid',
        headStyles: { fillColor: [79, 70, 229], textColor: [255, 255, 255] }, // Indigo 600
        styles: { fontSize: 10 }
    });

    // Auditor Footer
    const finalY = (doc as any).lastAutoTable.finalY;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(156, 163, 175);
    doc.text('This is an automated operational audit generated by the JewelMatrix Performance Engine.', 15, finalY + 20);
    doc.text('Scores are calculated based on task throughput and deadline adherence.', 15, finalY + 25);

    // Save PDF
    doc.save(`Performance_Report_${data.employeeName}_${format(new Date(), 'yyyyMMdd')}.pdf`);
}
